# Day 2 part 1 (messy as on phone)

def func(input):
  twos = 0
  threes = 0
  
  for term in input:
    listOfCharac={} 
    a2 = False
    a3 = False
    
    for s in term: 
      if s in listOfCharac.keys():
        listOfCharac[s]+=1 
      else: 
        listOfCharac[s]=1 
        
    for item in listOfCharac:
      value = listOfCharac[item]
      if value == 2:
        a2 = True
      if value == 3:
        a3 = True
    if a2:
      twos = twos + 1
    if a3:
      threes = threes + 1
  
  return twos * threes

def test(input, expected):
  output = func(input)
  matcher = "-"
  if (output == expected):
    matcher = "+"
  print("[" + matcher + "]" + str(output) + "~" + str(expected))


test(["abcdef","bababc","abbcde","abcccd", "aabcdd","abcdee","ababab"], 12)

input = "dghfbsyiznoumojleevappwqtr dghfbsyiznoumkjljevacpmqer dghfbbyizioumkjlxevacpwdtr dghfbsesznoumkjlxevacpwqkr dghfbsynznoumkjlxziacpwqtr cghfbsyiznjumkjlxevacprqtr dghfjsyizwoumkjlxevactwqtr dghfdsyfinoumkjlxevacpwqtr hghfbsyiznoumkjlxivacpwqtj dgcfbsyiznoumkjlxevacbuqtr dghfbsyiznoymnjlxevacpwvtr dfhfbsyiznoumkulxevacptqtr dghfasyiznovmkjlxevacpwqnr dghfbsyihnouikjlxevackwqtr dghfbayiznolmkjlyevacpwqtr jghfbsyiznoumnjldevacpwqtr dhhfbsyuznoumkjlxevakpwqtr nehfrsyiznoumkjlxevacpwqtr dghfbsyiznxdmkolxevacpwqtr dgpfbsyizwlumkjlxevacpwqtr yghfbsyiznoumkjlsevacpwqtm dghfssyiznoumkjlxevvcpwqjr dahfbsyiznoumkjlfevacpwqto duhfcsyiznouvkjlxevacpwqtr dghfbvyiznoumkjlrevacpwvtr dghfgsyiznoumknlxgvacpwqtr jghfbeyiznkumkjlxevacpwqtr daofbsyiznoumkjlxevampwqtr dghfbsyiznojmkjlxeracpcqtr dghnbsyiznouokjlxevaclwqtr dgifbsyiznoumkjlxevnspwqtr dgkfpsziznoumkjlxevacpwqtr dghfxsyijnoumkjlxevaccwqtr dghfbsyiznolmkjlwevzcpwqtr dkhfbsaiznoumkjlxevacpwqtg dghfbsygknoumkjlaevacpwqtr dghfbsyizizumkjlxevacpxqtr ighfbbyijnoumxjlxevacpwqtr dghfbsyizrouekjlxevacpwktr dghobsyiznoujkjlxevacnwqtr dghpbsyizyoumkjlxeaacpwqtr dghffsyiznoymkjlxevacewqtr dghkbssiznoumzjlxevacpwqtr dghfbsyawnoumkjlxevacpwjtr drhfbsyiznormkjlfevacpwqtr dghfbsoiznouwkjlxevacpwqtn dghfmsyiznoumkjlxlvecpwqtr dxhfbsyiznoumkjlxeeacvwqtr dghnbsyiznoumkjsxevacpwqur dghfbsyiznrujkjlxevacpwqtc dghfbstoznoumhjlxevacpwqtr dghfboyiznzumkjlvevacpwqtr dghfbsyiznjumkjlxevgcpwmtr dghfbsnizaoumkjlxevacpwetr dghfbsyirnoumkjoxevacplqtr dghfbsyiznoumkjlxavvckwqtr dghfbjdiznoumkjlxevacpwptr dghfbsywznoumkjlxeiacpwqcr djhfbsyizuoumkjlxelacpwqtr dghffsniznoumkjlxpvacpwqtr dghebsyizuoumkjlxevecpwqtr rghfbsyiznourkjcxevacpwqtr dghfbsyignoumkwlxenacpwqtr dghfbsyiznrufkjlxevacpwqth dgifbsyiznoumkjlxevacpjqnr dghfbsyiznoumkjbxevaxpwqtw dsufbsyizncumkjlxevacpwqtr dihfbsyiznoumujlxecacpwqtr dghfbiyiznoumkjlxevajpwqtn dghqbsyixnoumkjlrevacpwqtr dghfbsyiznouukjlxeuacpwqtx dghfbsyizyoumksfxevacpwqtr dghfbsiiznopfkjlxevacpwqtr eghfbsyidnoumkjlxexacpwqtr dghfbgyiznouwkjlwevacpwqtr dghfbsyyznoumkjlxevacwwqtf bghfbtypznoumkjlxevacpwqtr dghfbsyiznoumtjlxebacpwetr dghfbsgiznonmkplxevacpwqtr dghfbsyiznoumxjlxevanpwqpr dghfbsyiznwumujuxevacpwqtr dghxbsyiznoumkjzxevaypwqtr dghfbsyhznoumkjlxlvacpiqtr dghfbsyiznoumkjlxevzcnwqrr dvhfbsyiznoumkjluevacpzqtr dghcbsyiznoumkjlxmvacpwetr dghfbsyiznohmkjvxbvacpwqtr dghfzsyiznouokjlxevacpwqpr dghfbsyiznoumkjlxevachtqth dghfbsyiznoumkjlxjvacpfutr dghfbsyiznoumkjlxevsppwqtt dghfusyiznouakhlxevacpwqtr dghfbsyizcoumkjlxrvaipwqtr dghebsyipnoumfjlxevacpwqtr dgdfbsyiznoumkjlwevacpkqtr dghfbsyiznoumkjlcffacpwqtr dghfbsypznfumkjlxevacpwqar dghfbsyiznojmkjlxevgcpkqtr dghfbsyiznoumkjlaevlcpwstr dgafrsyiunoumkjlxevacpwqtr dghfbsyiznouqljlxevacrwqtr dyhkbsyiznokmkjlxevacpwqtr pghfbsciznoumkjlxevacpwvtr dghfbxyiznonmkjllevacpwqtr ighfbsyizxoumkjlxevacpzqtr dgffbsyoznoumkjlxevacpwqto hghfbsyiznoumkjlpevachwqtr dlhfosyiznoumkjldevacpwqtr dghfbsvizkoumkjlxvvacpwqtr dbafbsyiznozmkjlxevacpwqtr dghfbsyidnoumkjlxrvjcpwqtr dghfbsyiznfumkjlxeqacpwqta dghfbsfiznoumkjvxevacjwqtr dghfbsyimnoumrjlhevacpwqtr dghflsyiznoumkjlxevacpvqmr dghfbmfiznoumkjlxevacpdqtr dghfbsyizsouzkjlxevscpwqtr dghfksyiznoumimlxevacpwqtr dghfbsyiznoumkjlxevbwpwqur wghcbsyiznoumkjlkevacpwqtr kghfbioiznoumkjlxevacpwqtr dghfbsiizeoumkjlxmvacpwqtr dglfbsyilnoumkjlxevpcpwqtr dgqfbsylznoumkjlxevacpwqcr dglfhsyiznoumkjlxevacpwqdr dghfbsymznoumkjlxbvacpwqtb hghfbsyizhoumkjlxtvacpwqtr dghdbsyiznoumkjlxeiacpyqtr dohfbsyiznoumkjmxlvacpwqtr xhhfbsyiznoumkjlxegacpwqtr dlhfbsyiznoumkjlxnvahpwqtr dghfbsyiznovdpjlxevacpwqtr dgcfbsyiznoumkjlxevactwqdr dghfksyiknoumkjlxevacpwqcr ughfqsyiznoumkjlxevacpwctr dghfbjyiznoumkjlxsvacnwqtr dgwfbagiznoumkjlxevacpwqtr dghfbsyiznoumknlxevtcpwqdr jghfksyiznoumkjlxeoacpwqtr dghfbsyiznoimkjlwezacpwqtr dghfbsyiunoumkjlxeqacpwstr dghfbsyizjoumkwlxevaypwqtr dghfysriznoumkjlxevucpwqtr dghfbsygzjoumkjfxevacpwqtr dghfbhviznoumkjlxevacpwqtq dghfbsyiznoumkjvwevacpwqur dghfbsyiznoumtjlxevacplqnr yghfbsysznouykjlxevacpwqtr dgwfbsiiznoumkjlxevacfwqtr dghfbsyizooumkjlxevampiqtr dshfbsyiznoumkjlxevawpoqtr dghtbsyxznuumkjlxevacpwqtr dkhfblyiznoumkjlxevacpaqtr dgkfbsyiinoumkjlxegacpwqtr dghfbtxiznouhkjlxevacpwqtr dghfbsyiznoumkjlxkvmcpeqtr dghfbsyiznoumkjlghvacpwqmr dghfbsbizioumkjlcevacpwqtr dphfbsyizhoumkjwxevacpwqtr dghfbsyiznqumkjlugvacpwqtr dghfbsjinnoumkjlxevacpwetr mghfbsyiznoumkjlxfvacpjqtr dghfbsxiznoumkjlxetacwwqtr dghmbsyiznoumbjlxevacpwqyr dghfbsyiznwumkjlwevacmwqtr dgkfbsyiznotmkjlxevacpwstr dghfbsyiznouykjlxeiacuwqtr dghfbsynznbhmkjlxevacpwqtr dgyfbsyiznoumtjlbevacpwqtr dghfbftiznoumkjlxevacpwatr dghfvsyiznouikjlievacpwqtr dghfbsyiznodmkjlxevncpwqtz yfhfbsyiznoumkjluevacpwqtr dghfbzyiznoumhflxevacpwqtr dphfbsyizncumkjlxevacpwqtf dghfasyiznoumkjlxeaicpwqtr dgffbsyiznoumkjlzevacpwqsr dghfbsyiznoumkmxxcvacpwqtr dghffsyiznoumkjlxevacpwqre dghfbsyizndmmkjlxemacpwqtr dghfbsviznoamkjlxevappwqtr dghfbsyiznouckrlxevacpdqtr dgwfbsyiznyumkjlxevacpqqtr dujfbsyiznoumgjlxevacpwqtr dghobsailnoumkjlxevacpwqtr dghfkqyiznoumknlxevacpwqtr dghfbyypznoumkjlxevacpwatr wqhfbsyiznoumkjlxevzcpwqtr dghfbsyiznoumwjlxrvacppqtr dghfbsymznoumkflxevacplqtr dghfbsyiznounkjpgevacpwqtr ighfbsyijnoumxjlxevacpwqtr dghfbsyizroumkjllevncpwqtr dghfbsliznokmkjlxevacpwqtb dgefbsyiznoumkqlxevpcpwqtr dghfbtypznouzkjlxevacpwqtr dmhfbsyiznoumkjlxeyactwqtr vohfbsyiznoumkjlqevacpwqtr dgsfpsyiznodmkjlxevacpwqtr dghfzsyijnoumkjnxevacpwqtr dghfbayijroumkjlxevacpwqtr dghfbsyiznodmxjlxgvacpwqtr dghfbsyiznocmkjlxhvaipwqtr dghmbsyignoumkjlxevacpoqtr dghfbsyiznosmkjlncvacpwqtr dggfbsyiznuumkjlxevacpwqrr dghibsyilnoumkjlxevacowqtr dghfbsyiznoumkjluevbcowqtr dghfbsaiznyuvkjlxevacpwqtr dgnfxsyiznommkjlxevacpwqtr dghfbnyiznoumkjlsnvacpwqtr dghfssiiznoumkjlxavacpwqtr dghfbsyizneumajlxevacfwqtr dghfbsyiznoumkjlxevycpvptr qghfbsyizgoumkjlxevacpwttr vghfbsyiznoumkjlievaepwqtr dghfbsyiznoumejlxjvacpwdtr dghfbsyispoumkjlxevacpwqtg duhfbsyizpoumkjlxenacpwqtr dghfbsyifnoumkblxevacpnqtr bghfbsyxznoumkjleevacpwqtr dgtfbsyzpnoumkjlxevacpwqtr dghfbsyiznoumkjlsecacpwqth dghfqsyiznjumkjlxevawpwqtr dgcfbsyizboumkjlxevacqwqtr dghfbqyiznoumkjkxevacpwqtj dgyfbsyfznoumkjlievacpwqtr dghfdsyiznoumkplxevacpwdtr dphfbsyuznkumkjlxevacpwqtr dghfbsyiznoupkjitevacpwqtr dghfisyiznoamkjlxevacpwqwr dgufbsyiznoumkjlxivvcpwqtr dghfbvyiznoumkjlxevacvwqtz dghfbsyiqnxumkjlxbvacpwqtr dghubsyiznqumkflxevacpwqtr dghfbsyiznzumkjlxevacpdbtr dghfbsyiznoumkjlxehacpwwrr mghfbsyiznoumkjlxevacpwqbp dvhfbryiznoumkclxevacpwqtr dghbbsyiznotmkjlxevacpwqhr dghfrsyiznoomkjlxevacpwqto dghfbkyiznoumkjlxeracpxqtr dghfbfyizfoumkjlxevacpwjtr dghfbsyizqoulkjlxevacpwqtt dghfbsyiwnoumkjlxevacxwgtr dghfbsyiznormkjlgxvacpwqtr dghybsyizioumkjoxevacpwqtr dchfbsyiznoumkjlxyvacpwqtc dgyfbsyiznouckjlxewacpwqtr dakfbsyeznoumkjlxevacpwqtr"
print (func(input.split(" ")))